name: movieku
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dot_navigation_bar: ^1.0.1+4
  floating_bottom_navigation_bar: ^1.5.2
  floating_frosted_bottom_bar: ^0.0.1
  flutter:
    sdk: flutter
  flutter_carousel_slider: ^1.1.0
  get: 4.6.5
  shaky_animated_listview: ^0.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
